### ISSUE TITLE
How can i disconnect the lock completely ?

### ISSUE THREAD

**Issue by khanhduytran** [noke-inc/noke-mobile-library-android#5]
The lock is still send signal although i have called disconnect function and the lock state have changed to disconnect.

First i call scan function to unlock the lock. When the lock have been unlock, i left the lock open and call disconnect function. When i receive a disconnect state from the lock, i call scan function again. At this step the lock is still send signal to unlock.

I also try let the lock disconnect by itself and start scan again. But in this case the lock didn't send any signal until i press it.

**Comment by sapsley** [comment]
The lock does not broadcast bluetooth until the shackle is pressed.  Once the shackle is pressed, the lock will broadcast for 60 seconds, at which point it will go back to a sleep state and stop broadcasting.  This is by design to preserve battery.

If you wish to disconnect the lock completely and prevent it from connecting, you can remove the mac address from the device array which will prevent the mobile library from detecting the lock at all.
